
import { PlanetData } from './types';

const LRM = '\u200E';

export const SUN: PlanetData = {
  id: 'sun',
  name: 'השמש',
  englishName: 'The Sun',
  distanceFromSun: 'מרכז המערכת',
  water: 'אין (חם מדי)',
  atmosphere: 'גזים לוהטים (מימן והליום)',
  dayLength: '27 ימי ארץ',
  yearLength: '230 מיליון שנים',
  type: 'כוכב',
  color: '#fbbf24',
  size: 40,
  orbitalSpeed: 0,
  realSize: '1,392,700 ק"מ',
  moonsCount: 0,
  humanReached: false,
  explorationTools: 'SOHO, Parker Solar Probe',
  temperature: '5,500 מעלות',
  imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg',
  description: 'הכדור הלוהט שנותן לנו אור וחום. כמעט כל החומר במערכת השמש נמצא בתוכה!'
};

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'כוכב חמה',
    englishName: 'Mercury',
    distanceFromSun: '58 מיליון ק"מ',
    water: 'קרח מים עמוק במכתשים',
    atmosphere: 'כמעט ואין',
    dayLength: '59 ימי ארץ',
    yearLength: '88 ימי ארץ',
    type: 'ארצי',
    color: '#94a3b8',
    size: 6,
    orbitalSpeed: 5.0,
    realSize: '4,879 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'MESSENGER',
    temperature: `${LRM}-173°C עד 427°C`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Mercury_in_true_color.jpg',
    description: 'הכי קרוב לשמש ונע במהירות עצומה! ביום לוהט שם ובלילה קפוא מאוד.'
  },
  {
    id: 'venus',
    name: 'נוגה',
    englishName: 'Venus',
    distanceFromSun: '108 מיליון ק"מ',
    water: 'אין',
    atmosphere: 'סמיכה ורעילה מאוד',
    dayLength: '243 ימי ארץ',
    yearLength: '225 ימי ארץ',
    type: 'ארצי',
    color: '#fbbf24',
    size: 10,
    orbitalSpeed: 3.5,
    realSize: '12,104 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'Magellan',
    temperature: '462 מעלות (לוהט!)',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg',
    description: 'כוכב הלכת הכי חם במערכת השמש בגלל אפקט חממה קיצוני.'
  },
  {
    id: 'earth',
    name: 'כדור הארץ',
    englishName: 'Earth',
    distanceFromSun: '150 מיליון ק"מ',
    water: '71% מהשטח (אוקיינוסים)',
    atmosphere: 'חנקן וחמצן',
    dayLength: '24 שעות',
    yearLength: '365 ימים',
    type: 'ארצי',
    color: '#3b82f6',
    size: 11,
    orbitalSpeed: 2.8,
    realSize: '12,742 ק"מ',
    moonsCount: 1,
    moonsDetails: 'הירח שלנו',
    humanReached: true,
    explorationTools: 'לוויינים ותחנת החלל',
    temperature: `${LRM}-88°C עד 58°C`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/The_Earth_seen_from_Apollo_17.jpg',
    description: 'הבית היחיד שלנו. הפלנטה היחידה המוכרת שיש עליה חיים.'
  },
  {
    id: 'mars',
    name: 'מאדים',
    englishName: 'Mars',
    distanceFromSun: '228 מיליון ק"מ',
    water: 'קרח בקטבים',
    atmosphere: 'דלילה מאוד',
    dayLength: '24.6 שעות',
    yearLength: '687 ימים',
    type: 'ארצי',
    color: '#ef4444',
    size: 8,
    orbitalSpeed: 2.2,
    realSize: '6,779 ק"מ',
    moonsCount: 2,
    moonsDetails: 'פובוס ודימוס',
    humanReached: false,
    explorationTools: 'רובוטים (Perseverance)',
    temperature: `${LRM}-153°C עד 20°C`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/02/OSIRIS_Mars_true_color.jpg',
    description: 'הכוכב האדום. יעד מרכזי למחקר עתידי של בני אדם.'
  },
  {
    id: 'ceres',
    name: 'צרס',
    englishName: 'Ceres',
    distanceFromSun: '414 מיליון ק"מ',
    water: 'הרבה קרח מים',
    atmosphere: 'כמעט ואין',
    dayLength: '9 שעות',
    yearLength: '4.6 שנים',
    type: 'ננסי',
    color: '#a1a1aa',
    size: 4,
    orbitalSpeed: 1.8,
    realSize: '940 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'החללית Dawn',
    temperature: `${LRM}-105 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Ceres_-_RC3_-_Haulani_Crater_%2822381131691%29_%28cropped%29.jpg',
    description: 'העצם הגדול ביותר בחגורת האסטרואידים.'
  },
  {
    id: 'jupiter',
    name: 'צדק',
    englishName: 'Jupiter',
    distanceFromSun: '778 מיליון ק"מ',
    water: 'מעט ענני מים',
    atmosphere: 'גזים (מימן והליום)',
    dayLength: '10 שעות',
    yearLength: '12 שנים',
    type: 'גזי',
    color: '#d97706',
    size: 24,
    orbitalSpeed: 1.2,
    realSize: '139,820 ק"מ',
    moonsCount: 95,
    moonsDetails: 'אירופה, גנימד, איו, קליסטו',
    humanReached: false,
    explorationTools: 'החללית Juno',
    temperature: `${LRM}-110 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Jupiter.jpg',
    description: 'ענק הגזים. יש לו סערה ענקית (הכתם האדום) שמשתוללת מאות שנים.'
  },
  {
    id: 'saturn',
    name: 'שבתאי',
    englishName: 'Saturn',
    distanceFromSun: '1.4 מיליארד ק"מ',
    water: 'קרח מים (בטבעות)',
    atmosphere: 'גזית',
    dayLength: '10.7 שעות',
    yearLength: '29 שנים',
    type: 'גזי',
    color: '#f59e0b',
    size: 20,
    orbitalSpeed: 0.9,
    realSize: '116,460 ק"מ',
    moonsCount: 146,
    moonsDetails: 'טיטאן, אנסלדוס',
    humanReached: false,
    explorationTools: 'החללית Cassini',
    temperature: `${LRM}-140 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg',
    description: 'מפורסם בזכות מערכת הטבעות המרהיבה שלו העשויה מקרח ואבק.'
  },
  {
    id: 'uranus',
    name: 'אורנוס',
    englishName: 'Uranus',
    distanceFromSun: '2.9 מיליארד ק"מ',
    water: 'קרח וגז קפוא',
    atmosphere: 'קרה מאוד וכחולה',
    dayLength: '17 שעות',
    yearLength: '84 שנים',
    type: 'גזי',
    color: '#22d3ee',
    size: 16,
    orbitalSpeed: 0.6,
    realSize: '50,724 ק"מ',
    moonsCount: 28,
    humanReached: false,
    explorationTools: 'Voyager 2',
    temperature: `${LRM}-195 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Uranus2.jpg',
    description: 'ענק הקרח ששוכב על הצד - ציר הסיבוב שלו מוטה ב-98 מעלות.'
  },
  {
    id: 'neptune',
    name: 'נפטון',
    englishName: 'Neptune',
    distanceFromSun: '4.5 מיליארד ק"מ',
    water: 'קרח וגזים',
    atmosphere: 'רוחות חזקות מאוד',
    dayLength: '16 שעות',
    yearLength: '165 שנים',
    type: 'גזי',
    color: '#6366f1',
    size: 15,
    orbitalSpeed: 0.5,
    realSize: '49,244 ק"מ',
    moonsCount: 14,
    humanReached: false,
    explorationTools: 'Voyager 2',
    temperature: `${LRM}-201 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Neptune_Full.jpg',
    description: 'כוכב הלכת המרוחק ביותר מהשמש, בעל רוחות במהירות על-קולית.'
  },
  {
    id: 'pluto',
    name: 'פלוטו',
    englishName: 'Pluto',
    distanceFromSun: '5.9 מיליארד ק"מ',
    water: 'הרבה קרח',
    atmosphere: 'דלילה מאוד',
    dayLength: '6 ימי ארץ',
    yearLength: '248 שנים',
    type: 'ננסי',
    color: '#9ca3af',
    size: 4,
    orbitalSpeed: 0.4,
    realSize: '2,376 ק"מ',
    moonsCount: 5,
    moonsDetails: 'כארון (הירח הגדול)',
    humanReached: false,
    explorationTools: 'New Horizons',
    temperature: `${LRM}-225 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Pluto_in_True_Color_-_High-Res.jpg',
    description: 'כוכב לכת ננסי בחגורת קויפר, בעל אזור בצורת לב ענקי העשוי קרח חנקן.'
  },
  {
    id: 'charon',
    name: 'כארון',
    englishName: 'Charon',
    distanceFromSun: '5.9 מיליארד ק"מ',
    water: 'קרח מים',
    atmosphere: 'אין',
    dayLength: '6 ימי ארץ',
    yearLength: '248 שנים',
    type: 'ננסי',
    color: '#71717a',
    size: 3,
    orbitalSpeed: 0.4,
    realSize: '1,212 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'New Horizons',
    temperature: `${LRM}-220 מעלות`,
    imageUrl: 'https://www.nasa.gov/wp-content/uploads/2015/10/charon_color_final_small.jpg',
    description: 'הירח הגדול ביותר של פלוטו, כל כך גדול שהם מסתובבים זה סביב זה כזוג.'
  },
  {
    id: 'haumea',
    name: 'האומיה',
    englishName: 'Haumea',
    distanceFromSun: '6.4 מיליארד ק"מ',
    water: 'מעטפת קרח',
    atmosphere: 'אין',
    dayLength: '4 שעות',
    yearLength: '284 שנים',
    type: 'ננסי',
    color: '#d1d5db',
    size: 3,
    orbitalSpeed: 0.35,
    realSize: '1,632 ק"מ',
    moonsCount: 2,
    humanReached: false,
    explorationTools: 'VLT',
    temperature: `${LRM}-241 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Haumea_Artist_Impression.jpg/800px-Haumea_Artist_Impression.jpg',
    description: 'כוכב לכת ננסי בעל צורה ביצית משונה בגלל סיבובו המהיר במיוחד.'
  },
  {
    id: 'makemake',
    name: 'מאקה-מאקה',
    englishName: 'Makemake',
    distanceFromSun: '6.8 מיליארד ק"מ',
    water: 'קרח מתאן',
    atmosphere: 'זמנית',
    dayLength: '22 שעות',
    yearLength: '305 שנים',
    type: 'ננסי',
    color: '#fdba74',
    size: 3,
    orbitalSpeed: 0.3,
    realSize: '1,430 ק"מ',
    moonsCount: 1,
    humanReached: false,
    explorationTools: 'Hubble',
    temperature: `${LRM}-243 מעלות`,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Makemake_and_its_moon.jpg/800px-Makemake_and_its_moon.jpg',
    description: 'אחד העצמים הגדולים ביותר בחגורת קויפר החיצונית.'
  },
  {
    id: 'eris',
    name: 'אריס',
    englishName: 'Eris',
    distanceFromSun: '10 מיליארד ק"מ',
    water: 'קרח חנקן',
    atmosphere: 'קפואה',
    dayLength: '25 שעות',
    yearLength: '557 שנים',
    type: 'ננסי',
    color: '#f3f4f6',
    size: 4,
    orbitalSpeed: 0.2,
    realSize: '2,326 ק"מ',
    moonsCount: 1,
    humanReached: false,
    explorationTools: 'Keck',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Eris_and_Dysnomia.jpg/800px-Eris_and_Dysnomia.jpg',
    temperature: `${LRM}-240 מעלות`,
    description: 'כוכב לכת ננסי רחוק וקר מאוד, בעל מסה גדולה אפילו משל פלוטו.'
  }
];
