import { PlanetData } from './types';

const LRM = '\u200E';

export const SUN: PlanetData = {
  id: 'sun',
  name: 'השמש',
  englishName: 'The Sun',
  distanceFromSun: '0 ק"מ',
  water: 'אין (חם מדי)',
  atmosphere: 'פוטוספירה, כרומוספירה ועטרה (בעיקר מימן והליום)',
  dayLength: 'כ-27 ימי ארץ (משתנה לפי קווי רוחב)',
  yearLength: '230 מיליון שנים (מסביב לגלקסיה)',
  type: 'כוכב',
  color: '#fbbf24',
  size: 40,
  orbitalSpeed: 0,
  realSize: '1,392,700 ק"מ',
  moonsCount: 0,
  humanReached: false,
  explorationTools: 'SOHO, Parker Solar Probe',
  temperature: '5,500°C (פנים: 15 מיליון מעלות)',
  imageUrl: 'https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e000790/GSFC_20171208_Archive_e000790~orig.jpg',
  description: 'הכוכב המרכזי שסביבו הכל מסתובב. השמש מהווה 99.8% ממסת מערכת השמש כולה!'
};

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'כוכב חמה',
    englishName: 'Mercury',
    distanceFromSun: '58 מיליון ק"מ',
    water: 'קרח מים במכתשים קוטביים מוצלים',
    atmosphere: 'אקסוספירה דלילה מאוד (חמצן, נתרן, מימן)',
    dayLength: '59 ימי ארץ',
    yearLength: '88 ימי ארץ',
    type: 'ארצי',
    color: '#94a3b8',
    size: 6,
    orbitalSpeed: 3.5,
    realSize: '4,879 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'MESSENGER, BepiColombo',
    temperature: `${LRM}-173°C עד 427°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA15162/PIA15162~orig.jpg',
    description: 'הפלנטה הקטנה והקרובה ביותר לשמש. אין לו אטמוספירה שתשמור על החום, ולכן ההבדלים בין יום ללילה קיצוניים.'
  },
  {
    id: 'venus',
    name: 'נוגה',
    englishName: 'Venus',
    distanceFromSun: '108 מיליון ק"מ',
    water: 'אין (התאדו מזמן)',
    atmosphere: 'סמיכה מאוד ורעילה (96% פחמן דו-חמצני)',
    dayLength: '243 ימי ארץ',
    yearLength: '225 ימי ארץ',
    type: 'ארצי',
    color: '#fbbf24',
    size: 10,
    orbitalSpeed: 2.8,
    realSize: '12,104 ק"מ',
    moonsCount: 0,
    humanReached: false,
    explorationTools: 'Venera, Magellan, Akatsuki',
    temperature: '462°C (חממה לוהטת)',
    imageUrl: 'https://images-assets.nasa.gov/image/PIA00271/PIA00271~orig.jpg',
    description: 'התאום הלוהט של כדור הארץ. הלחץ על פני השטח חזק פי 90 מהלחץ אצלנו - כמו להיות קילומטר מתחת למים.'
  },
  {
    id: 'earth',
    name: 'כדור הארץ',
    englishName: 'Earth',
    distanceFromSun: '150 מיליון ק"מ',
    water: '71% משטח הפנים (נוזליים)',
    atmosphere: 'חנקן (78%) וחמצן (21%)',
    dayLength: '24 שעות',
    yearLength: '365.25 ימים',
    type: 'ארצי',
    color: '#3b82f6',
    size: 11,
    orbitalSpeed: 2.2,
    realSize: '12,742 ק"מ',
    moonsCount: 1,
    moonsDetails: 'הירח (Luna)',
    humanReached: true,
    explorationTools: 'לוויינים, תחנת החלל הבינלאומית',
    temperature: `${LRM}-88°C עד 58°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/AS17-148-22727/AS17-148-22727~orig.jpg',
    description: 'הבית שלנו. הפלנטה היחידה המוכרת המאפשרת קיום חיים בזכות המרחק המדויק מהשמש ואטמוספירה מגנה.'
  },
  {
    id: 'mars',
    name: 'מאדים',
    englishName: 'Mars',
    distanceFromSun: '228 מיליון ק"מ',
    water: 'קרח בקטבים ומתחת לקרקע',
    atmosphere: 'דלילה (בעיקר פחמן דו-חמצני)',
    dayLength: '24.6 שעות',
    yearLength: '687 ימי ארץ',
    type: 'ארצי',
    color: '#ef4444',
    size: 8,
    orbitalSpeed: 1.8,
    realSize: '6,779 ק"מ',
    moonsCount: 2,
    moonsDetails: 'פובוס ודימוס',
    humanReached: false,
    explorationTools: 'Perseverance, Curiosity, Insight',
    temperature: `${LRM}-153°C עד 20°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA02653/PIA02653~orig.jpg',
    description: 'הכוכב האדום. בעבר היו בו נהרות ואגמים, וכיום הוא היעד המרכזי למחקר עתידי של התיישבות אנושית.'
  },
  {
    id: 'jupiter',
    name: 'צדק',
    englishName: 'Jupiter',
    distanceFromSun: '778 מיליון ק"מ',
    water: 'מעט אדים בעננים העליונים',
    atmosphere: 'ענקית (מימן והליום)',
    dayLength: '9.9 שעות',
    yearLength: '11.8 שנות ארץ',
    type: 'גזי',
    color: '#d97706',
    size: 24,
    orbitalSpeed: 1.1,
    realSize: '139,820 ק"מ',
    moonsCount: 95,
    moonsDetails: 'אירופה, גנימד, איו, קליסטו',
    humanReached: false,
    explorationTools: 'Juno, Galileo, Voyager',
    temperature: `${LRM}-110°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA04866/PIA04866~orig.jpg',
    description: 'מלך כוכבי הלכת. הוא כל כך גדול שכל שאר הפלנטות יכולות להיכנס בתוכו פעמיים!'
  },
  {
    id: 'saturn',
    name: 'שבתאי',
    englishName: 'Saturn',
    distanceFromSun: '1.4 מיליארד ק"מ',
    water: 'קרח מים (מהווה את רוב הטבעות)',
    atmosphere: 'גזית (מימן והליום)',
    dayLength: '10.7 שעות',
    yearLength: '29.4 שנות ארץ',
    type: 'גזי',
    color: '#f59e0b',
    size: 20,
    orbitalSpeed: 0.8,
    realSize: '116,460 ק"מ',
    moonsCount: 146,
    moonsDetails: 'טיטאן, אנסלדוס',
    humanReached: false,
    explorationTools: 'Cassini-Huygens, Voyager',
    temperature: `${LRM}-140°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA01364/PIA01364~orig.jpg',
    description: 'מפורסם בטבעות המרהיבות שלו. אם היה אמבטיה מספיק גדולה, שבתאי היה צף בה כי הוא פחות צפוף ממים.'
  },
  {
    id: 'uranus',
    name: 'אורנוס',
    englishName: 'Uranus',
    distanceFromSun: '2.9 מיליארד ק"מ',
    water: 'קרח מים, מתאן ואמוניה',
    atmosphere: 'קרה מאוד (מימן, הליום ומתאן שנותן לו צבע כחול)',
    dayLength: '17.2 שעות',
    yearLength: '84 שנות ארץ',
    type: 'גזי',
    color: '#22d3ee',
    size: 16,
    orbitalSpeed: 0.5,
    realSize: '50,724 ק"מ',
    moonsCount: 28,
    moonsDetails: 'טיטניה, אוברון, אריאל',
    humanReached: false,
    explorationTools: 'Voyager 2, JWST',
    temperature: `${LRM}-195°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA00032/PIA00032~orig.jpg',
    description: 'ענק הקרח השוכב על צידו. הוא מסתובב בזווית של 98 מעלות, מה שיוצר עונות שנה קיצוניות שנמשכות עשורים.'
  },
  {
    id: 'neptune',
    name: 'נפטון',
    englishName: 'Neptune',
    distanceFromSun: '4.5 מיליארד ק"מ',
    water: 'קרח וגזים קפואים',
    atmosphere: 'סוערת (מימן, הליום ומתאן)',
    dayLength: '16.1 שעות',
    yearLength: '165 שנות ארץ',
    type: 'גזי',
    color: '#6366f1',
    size: 15,
    orbitalSpeed: 0.4,
    realSize: '49,244 ק"מ',
    moonsCount: 14,
    moonsDetails: 'טריטון (ירח שמתקרב לפלנטה)',
    humanReached: false,
    explorationTools: 'Voyager 2',
    temperature: `${LRM}-201°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA01492/PIA01492~orig.jpg',
    description: 'הפלנטה הרחוקה ביותר. נושבות בה הרוחות החזקות ביותר במערכת השמש, שמגיעות למהירות של 2,100 קמ"ש.'
  },
  {
    id: 'pluto',
    name: 'פלוטו',
    englishName: 'Pluto',
    distanceFromSun: '5.9 מיליארד ק"מ',
    water: 'קרח מים וחנקן קפוא',
    atmosphere: 'דלילה ומשתנה (חנקן, מתאן ופחמן חד-חמצני)',
    dayLength: '153 שעות',
    yearLength: '248 שנות ארץ',
    type: 'ננסי',
    color: '#9ca3af',
    size: 4,
    orbitalSpeed: 0.3,
    realSize: '2,376 ק"מ',
    moonsCount: 5,
    moonsDetails: 'כארון, ניקס, הידרה',
    humanReached: false,
    explorationTools: 'New Horizons',
    temperature: `${LRM}-225°C`,
    imageUrl: 'https://images-assets.nasa.gov/image/PIA19952/PIA19952~orig.jpg',
    description: 'הפלנטה הננסית האהובה. ב-2006 הוא "הורד בדרגה" אך נותר אחד העולמות המרתקים ביותר בקצה המערכת.'
  }
];